### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by homa1978** [greaselovely/KineticLull#6]
After login I get the following error: Server Error (500)

No message in the log

Any hints for troubleshooting ?

**Comment by greaselovely** [comment]
Did you use the shell scripts for python install and setup?  It feels like there is something not installed or a module not being used. Let me know and I’ll see if I can help you through it with next steps.

**Comment by homa1978** [comment]
Yes I use Ubuntu 22.04 and used python install script and setup script

**Comment by greaselovely** [comment]
I realize that I made a mistake and that the database is missing in the repo and it's not getting rebuilt correctly / at all when you start the app.  You should be able to either download the [db.sqlite3 file directly](https://github.com/greaselovely/KineticLull/blob/main/db.sqlite3) or remove the entire project, clone and run through the scripts again.  Either way should get you operational.  Sorry for the trouble.  As a side note, in the root of KineticLull you will find a logs directory that gets created and the log inside should be able to tell you what's happening within the app if you need future troubleshooting.  Thanks for trying the app also!

Would you mind reporting back if this solves your problem so I can close this?

**Comment by greaselovely** [comment]
Checking in to see if you are up and running.  I'm going to close this in a day if I don't hear back.
